FROM node:20-alpine

WORKDIR /app

# Cài ffmpeg
RUN apk add --no-cache ffmpeg

# Copy package.json và package-lock.json
COPY package*.json ./

# Cài production dependencies
RUN npm install --production

# Copy toàn bộ source code
COPY . .

# Khởi chạy worker đã build (đảm bảo bạn đã build TS ra dist trước)
CMD ["node", "dist/worker/process-video-worker.js"]
