FROM node:20

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm install -g typescript

RUN npx tsc -p tsconfig.worker.json

ENV PORT=8080

# Nếu bạn cần load biến môi trường từ .env (dotenv)
CMD ["node", "-r", "dotenv/config", "dist/worker/process-video-worker.js"]

# Nếu không dùng dotenv, dùng lệnh này thay thế:
# CMD ["node", "dist/worker/process-video-worker.js"]
