FROM node:20

WORKDIR /app

# Cài ffmpeg (bản Debian)
RUN apt-get update && apt-get install -y ffmpeg

# Cài thư viện Node.js
COPY package.json package-lock.json ./
RUN npm install

# Copy mã nguồn và build TypeScript
COPY . .
RUN npx tsc -p tsconfig.worker.json

EXPOSE 8080
ENV PORT=8080

CMD ["node", "dist/worker/process-video-worker.js"]
