FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# ✅ Build đúng cấu hình cho worker
RUN npm run build:upload-service

ENV PORT=8080
EXPOSE 8080

CMD ["node", "dist/src/dummy-upload.js"]
