# Dockerfile.clean
FROM node:20

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .

# ✅ Build toàn bộ worker từ TypeScript
RUN npm run build:worker

ENV PORT=8080

# ✅ Gọi đúng file JS tương ứng
CMD ["node", "dist/worker/clean-video-worker.js"]
