FROM node:20

WORKDIR /app

# 1. Cài package
COPY package*.json ./
RUN npm install

# 2. Copy toàn bộ source cần thiết
COPY tsconfig.worker.json ./
COPY worker ./worker
COPY dist ./dist

# 3. Nếu muốn build TypeScript trong Docker:
# RUN npm install -g typescript
# RUN npx tsc -p tsconfig.worker.json

ENV PORT=8080

CMD ["node", "dist/worker/clean-video-worker.js"]
