FROM node:18-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY tsconfig.worker.json ./
COPY worker/ ./worker/
RUN npx tsc -p tsconfig.worker.json

FROM node:18-alpine

WORKDIR /app
COPY --from=build /app/dist ./dist
COPY package*.json ./

RUN npm ci --only=production

CMD ["node", "dist/worker/process-video-worker2.js"]
