apiVersion: v1
kind: Service
metadata:
  name: delete-service
  namespace: livekit
spec:
  type: LoadBalancer  # ✅ Đã đổi từ ClusterIP
  selector:
    app: delete-service
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002
