apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-service
  namespace: livekit
spec:
  replicas: 0
  selector:
    matchLabels:
      app: delete-service
  template:
    metadata:
      labels:
        app: delete-service
    spec:
      containers:
      - name: delete
        image: gcr.io/onlook-main/onlook-delete:v1
        envFrom:
        - secretRef:
            name: livekit-secret
        ports:
        - containerPort: 4002
