apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: livekit-ingress-scaled
  namespace: livekit
spec:
  scaleTargetRef:
    name: livekit-ingress
    kind: Deployment
  pollingInterval: 15
  cooldownPeriod: 300
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-server.monitoring.svc.cluster.local
        metricName: livekit_ingress_available
        query: livekit_ingress_available
        threshold: "1"
