apiVersion: apps/v1
kind: Deployment
metadata:
  name: livekit-ingress
  namespace: livekit
spec:
  replicas: 0
  selector:
    matchLabels:
      app: livekit-ingress
  template:
    metadata:
      labels:
        app: livekit-ingress
    spec:
      containers:
        - name: ingress-worker
          image: gcr.io/onlook-main/worker-ingress:v1
          ports:
            - containerPort: 4001
          envFrom:
            - secretRef:
                name: livekit-secret
