apiVersion: apps/v1
kind: Deployment
metadata:
  name: livekit-ingress
  namespace: livekit
spec:
  replicas: 0
  selector:
    matchLabels:
      app: livekit-ingress
  template:
    metadata:
      labels:
        app: livekit-ingress
    spec:
      containers:
      - name: ingress
        image: gcr.io/onlook-main/onlook-ingress:v1
        envFrom:
        - secretRef:
            name: livekit-secret
        ports:
        - containerPort: 4001
